title: Coffee Bot
description: Raspberry Pi Coffee Maker Automation with Servo Control
theme: just-the-docs
color_scheme: dark

# URLs
url: "https://ninjageoff.github.io"
baseurl: "/coffee_bot"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include/Exclude files
include:
  - _config.yml
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugin settings
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-remote-theme

# Plugin configurations
relative_links:
  enabled: true
  collections: false

optional_front_matter:
  remove_originals: false

titles_from_headings:
  enabled: true
  strip_title: true
  collections: false

# Navigation
collections:
  docs:
    output: true
    permalink: /:collection/:path/